/* eslint-disable camelcase */

const langEn = {
    nav:          [{ label: 'Map of payments PB', link: 'posts' }, { label: 'Statistics', link: 'statemap' }],
    search:       'Search',
    map:          'Map',
    statistics:   'Statistics',
    generalStat:  'General statistics',
    updated:      'Updated',
    branch:       'Branch',
    active:       'Active',
    working:      'Working',
    nonworking:   'Non-working',
    cause:        'Сause',
    state:        'State',
    quantity:     'Count unavailable',
    back:         'Back',
    device:       'Device',
    reason:       'Cause',
    adress:       'Adress',
    linkToQB:     'Critical services',
    point:        'Service point',
    pointTSO:     'Point',
    shops:        'Shop',
    total:        'Total',
    status:       'Status',
    //Pagination
    of:           'of',
    itemsPerPage: 'Items per page:',
    nextPage:     'Next page',
    lastPage:     'Last page',
    prewPage:     'Previous page',
    firstPage:    'First page',
    expand:       'Expand',
    collapse:     'Collapse',
    quantityPos:  'Amount',
    posMap:       'Map POS',
    scale:        'Scale',

    filtersAbsolute: 'Absolute units',
    filtersRelative: 'Relative units',
    logout:          'Logout',

    table_1_Title:         'Mass failures',
    table_1_PC:            'PC',
    table_1_Start:         'Date Start',
    table_1_End:           'Date End',
    table_1_Failure:       'Failure (description)',
    table_1_2_Description: '*Affects the work of all branches',

    table_2_Title:       'PC instability',
    table_2_PC:          'Name PC',
    table_2_Responsible: 'Responsible',
    table_2_Available:   'Acceptable % errors',
    table_2_Amt:         'Amt errors',
    table_2_Errors:      '% errors',

    table_3_Title:   'Local problems',
    table_3_Branch:  'Branch',
    table_3_Name:    'Name',
    table_3_cause_1: 'Point of service not occupied',
    table_3_cause_2: 'No connection',
    table_3_cause_3: 'No electricity',
    table_3_cause_4: 'Cash terminal out of order',

    heatmapTitle:  'Heat map P24',
    count_online:  'Users',
    select_online: 'Online',
    select_day:    'day',
    select_days:   'days',
    select_all:    'All',
    widgetZoom:    'Reset zoom',
};

const langRu = {
    nav:          [{ label: 'Карта платежей ПБ', link: 'posts' }, { label: 'Статистика', link: 'statemap' }],
    search:       'Поиск',
    map:          'Карта',
    statistics:   'Статистика',
    generalStat:  'Общая статистика',
    updated:      'Обновлено ',
    branch:       'Отделение',
    available:    'Доступно',
    notAvailable: 'Недоступно',
    active:       'Активные',
    working:      'Рабочие',
    nonworking:   'Нерабочие',
    cause:        'Причина',
    state:        'Состояние',
    quantity:     'Кол-во недоступных',
    back:         'Назад',
    device:       'Устройство',
    reason:       'Причина',
    adress:       'Адрес',
    linkToQB:     'Критичные сервисы',
    point:        'Точка обслуживания',
    pointTSO:     'Точка',
    shops:        'Магазин',
    total:        'Всего',
    status:       'Состояние',
    //Pagination
    of:           'из',
    itemsPerPage: 'Строк на странице:',
    nextPage:     'Next page',
    lastPage:     'Last page',
    prewPage:     'Previous page',
    firstPage:    'First page',
    expand:       'Развернуть',
    collapse:     'Свернуть',
    quantityPos:  'Количество',
    posMap:       'Карта POS',
    scale:        'Масштаб',

    filtersAbsolute: 'Абсолютные единицы',
    filtersRelative: 'Относительные единицы',
    logout:          'Выход',

    table_1_Title:         'Массовые сбои',
    table_1_PC:            'ПК',
    table_1_Start:         'Дата возникновения проблемы',
    table_1_End:           'Дата решения проблемы (ориентировочно)',
    table_1_Failure:       'Сбой (описание)',
    table_1_2_Description: '*Влияет на работу всех отделений',

    table_2_Title:       'Стабильность работы ПК',
    table_2_PC:          'Наименование ПК',
    table_2_Responsible: 'Ответственный',
    table_2_Available:   'Допустимый % ошибок',
    table_2_Amt:         'Кол-во ошибок',
    table_2_Errors:      '% ошибок',

    table_3_Title:   'Локальные проблемы',
    table_3_Branch:  'Бранч',
    table_3_Name:    'Наименование',
    table_3_cause_1: 'Не занята точка обслуживания',
    table_3_cause_2: 'Проблемы с сетью',
    table_3_cause_3: 'Нет электроэнергии',
    table_3_cause_4: 'Не работает Cash-терминал',

    heatmapTitle:  'Тепловая карта П24',
    count_online:  'Пользователи',
    select_online: 'Онлайн',
    select_day:    'день',
    select_days:   'дней',
    select_all:    'Всего',

    widgetZoom: 'Сбросить масштаб',

};

const langUa = {
    nav:             [{ label: 'Мапа платежiв ПБ', link: 'posts' }, { label: 'Статистика', link: 'statemap' }],
    search:          'Пошук',
    map:             'Мапа',
    statistics:      'Статистика',
    generalStat:     'Загальна статистика',
    updated:         'Оновлено',
    branch:          'Відділення',
    available:       'Доступно',
    notAvailable:    'Недоступно',
    active:          'Активні',
    working:         'Робочі',
    nonworking:      'Неробочі',
    cause:           'Причина',
    state:           'Стан',
    quantity:        'К-сть недоступних',
    back:            'Назад',
    device:          'Пристрій',
    reason:          'Причина',
    adress:          'Aдреса',
    linkToQB:        'Критичні сервіси',
    point:           'Точка обслуговування',
    pointTSO:        'Точка',
    shops:           'Магазин',
    total:           'Всього',
    status:          'Стан',
    //Pagination
    of:              'з',
    itemsPerPage:    'Рядків на сторінці:',
    nextPage:        'Next page',
    lastPage:        'Last page',
    prewPage:        'Previous page',
    firstPage:       'First page',
    expand:          'Развернути',
    collapse:        'Згорнути',
    quantityPos:     'Kількість',
    posMap:          'Мапа POS',
    scale:           'Масштаб',
    filtersAbsolute: 'Абсолютні одиниці',
    filtersRelative: 'Відносні одиниці',
    logout:          'Вихід',

    table_1_Title:         'Масові збої',
    table_1_PC:            'ПК',
    table_1_Start:         'Дата виникнення проблеми',
    table_1_End:           'Дата рішення проблеми (орієнтовно)',
    table_1_Failure:       'Збій (описання)',
    table_1_2_Description: '*Впливає на роботу всіх відділень',

    table_2_Title:       'Стабільність роботи ПК',
    table_2_PC:          'Назва ПК',
    table_2_Responsible: 'Відповідальний',
    table_2_Available:   'Доступний % помилок',
    table_2_Amt:         'Кіл-ть помилок',
    table_2_Errors:      '% помилок',

    table_3_Title:   'Локальні проблеми',
    table_3_Branch:  'Бранч',
    table_3_Name:    'Назва',
    table_3_cause_1: 'Не зайнята точка обслуговування',
    table_3_cause_2: 'Проблеми з мережею',
    table_3_cause_3: 'Немає електроенергії',
    table_3_cause_4: 'Не працює Cash-термінал',

    heatmapTitle:  'Теплова карта П24',
    count_online:  'Користувачі',
    select_online: 'Онлайн',
    select_day:    'день',
    select_days:   'днiв',
    select_all:    'Всього',

    widgetZoom: 'Скинути масштабування',

};

export {
    langRu, langEn, langUa
};
